# Generated by Django 5.1.3 on 2024-12-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiClass', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiClass.category'),
        ),
    ]
