# Generated by Django 5.1.4 on 2025-03-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch1', '0002_detaileddata_alter_csvdata_field1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='field10',
            field=models.CharField(default='', max_length=255, verbose_name='Field Ten'),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='field4',
            field=models.CharField(default='', max_length=255, verbose_name='Field Four'),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='field5',
            field=models.CharField(default='', max_length=255, verbose_name='Field Five'),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='field6',
            field=models.CharField(default='', max_length=255, verbose_name='Field Six'),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='field7',
            field=models.CharField(default='', max_length=255, verbose_name='Field Seven'),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='field8',
            field=models.CharField(default='', max_length=255, verbose_name='Field Eight'),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='field9',
            field=models.CharField(default='', max_length=255, verbose_name='Field Nine'),
        ),
        migrations.AddField(
            model_name='detaileddata',
            name='field10',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='detaileddata',
            name='field4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='detaileddata',
            name='field5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='detaileddata',
            name='field6',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='detaileddata',
            name='field7',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='detaileddata',
            name='field8',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='detaileddata',
            name='field9',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='field1',
            field=models.CharField(default='', max_length=255, verbose_name='Field One'),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='field2',
            field=models.CharField(default='', max_length=255, verbose_name='Field Two'),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='field3',
            field=models.CharField(default='', max_length=255, verbose_name='Field Three'),
        ),
        migrations.AlterField(
            model_name='detaileddata',
            name='field1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='detaileddata',
            name='field2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='detaileddata',
            name='field3',
            field=models.CharField(default='', max_length=255),
        ),
    ]
