# Generated by Django 5.1.4 on 2025-03-01 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch1', '0003_csvdata_field10_csvdata_field4_csvdata_field5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='field10',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='field4',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='field5',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='field6',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='field7',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='field8',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='field9',
        ),
        migrations.RemoveField(
            model_name='detaileddata',
            name='field10',
        ),
        migrations.RemoveField(
            model_name='detaileddata',
            name='field4',
        ),
        migrations.RemoveField(
            model_name='detaileddata',
            name='field5',
        ),
        migrations.RemoveField(
            model_name='detaileddata',
            name='field6',
        ),
        migrations.RemoveField(
            model_name='detaileddata',
            name='field7',
        ),
        migrations.RemoveField(
            model_name='detaileddata',
            name='field8',
        ),
        migrations.RemoveField(
            model_name='detaileddata',
            name='field9',
        ),
    ]
