# Generated by Django 5.1.4 on 2025-02-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(default=0)),
                ('product_code', models.IntegerField(default=0)),
                ('gst', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
